name: Test Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run app using docker compose
        run: cd example_app && docker compose up -d
      # - name: Make request using docker
      #   run: docker run --network container:app-server appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
      # - name: Make a request to the app
      #   run: curl --retry 10 --retry-delay 5 --retry-all-errors localhost:8000
      - name: Make a request to the app
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 5
          max_attempts: 5
          retry_wait_seconds: 5
          command: curl localhost:8000
