name: Test Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run app using docker compose
        run: cd example_app && docker compose up -d
      - name: Make a request to the app
        run: curl --retry 10 --max-time 10 localhost:8000
