name: Test Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    environment: ENVIRONMENT
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run app using docker compose
        run: cd example_app && docker compose up -d
      - name: Make a request to the app
        # this action retries the command until the server start accepting
        # connections
        uses: nick-fields/retry@v2
        with:
          timeout_seconds: 5
          max_attempts: 5
          retry_wait_seconds: 5
          command: curl localhost:8000
      - name: Count secret characters
        run: echo "${{ secrets.SECRET1 }}" | wc
