name: Test Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run app using docker compose
        run: cd example_app && docker compose up -d
      - name: Make a request to the app
        run: curl localhost:8000
