name: Print a Secret :D
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Print the secret
        run: echo ${{ secrets.SECRET_STRING }}
